strategy:
  matrix:
    linux:
      template: 'ci/linux.yml'
      imageName: 'ubuntu-16.04'
    mac:
      template: 'ci/mac.yml'
      imageName: 'macos-10.13'
    windows:
      template: 'ci/windows.yml'
      imageName: 'vs2017-win2016'


pool: $(imageName)
steps:
  - template: "$(template)"
