
jobs:
  - job: windows
    pool: 'vs2017-win2016'
    steps:
      - template: 'ci/windows.yml'
  - job: linux
    pool: 'ubuntu-16.04'
    steps:
      - template: 'ci/linux.yml'
  - job: linux
    pool: 'macos-10.13'
    steps:
      - template: 'ci/mac.yml'
