trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - ci/*
pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - ci/*

stages:
  - stage: build
    jobs:
      - job: windows
        pool:
          vmImage: 'vs2017-win2016'
        steps:
          - template: './ci/windows.yml'
      - job: linux
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - template: './ci/linux.yml'
      - job: mac
        pool:
          vmImage: 'macos-10.13'
        steps:
          - template: './ci/mac.yml'


  - stage: deploy
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - job: 'GitHub'
        pool:
          vmImage: 'vs2017-win2016'
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: current
              buildVersionToDownload: latest
              artifactName: drop
              downloadPath: '$(System.ArtifactsDirectory)' 
          - powershell: |
              cd $(System.ArtifactsDirectory)
              $version = ((./drop/demo.exe --version) -replace 'demo').trim()
              Write-Host "##vso[build.updatebuildnumber]v$version"
          - task: GitHubRelease@0
            inputs:
              gitHubConnection: github_smurawski
              repositoryName: smurawski/demo-up
              action: create
              target: '$(Build.SourceVersion)'
              tagSource: manual
              tag: $(Build.BuildNumber)
              assets: '$(System.ArtifactsDirectory)/drop/*' 