[package]
name = "demo"
version = "0.0.1"
authors = ["Steven Murawski"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.0"
clap = "2.33.0"
git2 = "0.8.0"
reqwest = "0.9.2"
